config/routes.rb
StudentAdmin::Application.routes.draw do
  devise_for :teachers
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :students
  resources :students do
    collection do
      get :stats
    end
  end
  root :to => "students#index"

  

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)      default(""), not null
#  nickname               :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  slug                   :string(255)
#  encrypted_password     :string(255)      default("")
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  invitation_token       :string(255)
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string(255)
#

class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :works
  has_many :tasks, through: :works

  extend FriendlyId
  friendly_id :nickname, use: :slugged

  validates :name, :nickname, :email, presence: true

  def available_tasks
    Task.all - self.tasks - Task.where(one_time: true).select{|task| task.students.any? }
  end

  def sum_points
    self.tasks.inject(0){|sum, task| sum + task.points}
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :string(255)
#  points      :integer
#  created_at  :datetime
#  updated_at  :datetime
#  business    :boolean          default(FALSE), not null
#  one_time    :boolean
#  parent_id   :integer
#

class Task < ActiveRecord::Base
  has_many :works
  has_many :students, through: :works
  belongs_to :parent, class_name: "Task"
  has_many :children, class_name: "Task", foreign_key: "parent_id"
  after_create :send_user_notification

  default_scope { order('tasks.created_at DESC') }

  scope :available, -> {all - joins(:works).where(one_time: true, works: {state: [:in_progress, :finished]})}

  def available?
    if self.one_time
      works.select(state: [:in_progress, :finished]).empty?
    else
      true
    end
  end

  def send_user_notification
    NewTaskMailer.new_task(self).deliver
  end
end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  task_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  state      :string(255)
#

class Work < ActiveRecord::Base
  has_and_belongs_to_many :students
  belongs_to :task

  after_create :send_user_notification

  state_machine :initial => :in_progress do

    event :finish do
      transition :in_progress => :finished
    end
  end

  def send_user_notification
    self.students.each do |student|
      WorkMailer.new_work(self, student).deliver
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
require 'googlecharts'

class StudentsController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @students = Student.all
    @tasks = Task.all
  end

  def show
    @student = Student.friendly.find(params[:id])
  end

  def stats
    @students = Student.all
    @student_points = Gchart.radar(
                        data: @students.map{|stud| stud.works.inject(0){|m,w| m + w.task.points} },
                        labels: @students.map(&:nickname),
                        #legend: @students.map(&:name),
                        size: '600x500'
    )
    @student_points2 = Gchart.pie(
        data: @students.map{|stud| stud.works.inject(0){|m,w| m + w.task.points} },
        #labels: @students.map(&:name),
        legend: @students.map(&:nickname),
        theme: :thirty7signals,
        size: '600x500'
    )
    data = @students.map{|stud| [stud.works.inject(0){|m,w| m + w.task.points}, stud.nickname] }.group_by{|x| x.first }.values
    @line_chart = Gchart.bar(
        data: data.map{|a| a.first.first},
        legend: data.map{|a| a.first.first.to_s + ': ' + a.inject(''){|m,n| m + n.last + ', '}},
        size: '600x500'
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails 4 Business</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="<%= "page-#{params[:controller]} page-#{params[:controller]}-#{params[:action]}"%>">

    <div class="container">

        <nav class="navbar navbar-default _navbar-fixed-top" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Rails 4 Business</a>
          </div>


          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
              <li><%= link_to 'Stats', stats_students_path %></li>
              <% if student_signed_in? %>
                <li><%= link_to 'Edit profile', edit_student_registration_path %> </li>
                <li><%= link_to "Logout", destroy_student_session_path, method: :delete %>	</li>
              <% else %>
                <li><%= link_to "Login", new_student_session_path %>	</li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="http://AppMaintainers.com"><%= image_tag 'app-maintainers.png', class: 'am-logo' %>an App Maintainers project</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </nav>

      <div class="marketing-message">
        <%= image_tag 'marketing-message-bg.png' %>
      </div>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>

        <div class="clearfix"></div>

        <div class="copyright visible-desktop visible-tablet hidden-phone">
          ★★★ This is an App Maintainers project, crafted in Budapest ★★★<br>
          <span>All rights reserved by Attila Juhász and App Maintainers Ltd. <br>
            "Rails", "Ruby on Rails", and the Rails logo are registered trademarks of David Heinemeier Hansson.</span>
        </div>
        <div class="copyright-mob hidden-desktop hidden-tablet visible-phone">
          ★★★<br> App Maintainers project <br>crafted in Budapest <br>★★★<br>
          <span>All rights reserved by Attila Juhász and App Maintainers Ltd. <br>
          Rails", "Ruby on Rails", and the Rails logo are registered trademarks of <br>David Heinemeier Hansson.</span>
        </div>
    </div>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/students/_student.html.erb
<% @students.each do |student| %>
	<li class="student pull-left">
    	<%= link_to student.nickname, student %>
    </li>
<% end %>

app/views/students/_tasks.html.erb
<ul>
  <% tasks.each do |task| %>
      <li class="task pull-left">
        <p class="<%= 'finished' unless task.available? %>">
          <span class="<%= 'business' if task.business %>">
             <%= content_tag(:b, "#{'★' * task.points}") %>
          </span>
          <%= task.description %><br>
        </p>
      </li>
  <% end %>
</ul>

app/views/students/index.html.erb
<h1>Students</h1>

<ul>
  <%= render partial: 'student' %>
</ul>

<div class="clearfix"></div>

<h1>Tasks</h1>
<%= render partial: "tasks", locals: {tasks: @tasks} %>

app/views/students/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

    <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/students/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/students/show.html.erb
<div class="container centered">
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @student.name %>
      </h1>
      <%= render "tasks", tasks: @student.tasks %>
    </div>
    </section>
  </aside>
</div>
</div>

app/views/students/stats.html.erb
<%= image_tag @student_points %>
<%= image_tag @student_points2 %>
<%= image_tag @line_chart %>